language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
#    - sys-img-armeabi-v7a-android-17

    # Licenses
    # - 'android-sdk-license-.+'
    # - 'google-gdk-license-.+'
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

script: ./gradlew assembleDebug
